spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cms?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: peak
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true

